name: NPM/Esy CI (install, build and test)

trigger:
- stable
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global esy@latest
    npm run build
    npm run lint-fmt
    npm run test
  displayName: 'esy/dune install, build and test'
